In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arrzeroes = np.array(89)
print (np.ndim(arrzeroes))

0


In [5]:
arr2 = np.array([[3,2],[4,3]])
arr2.ndim

2

In [6]:
np.size(arr2)

4

check memory

In [9]:
arr2.nbytes
arr2.dtype

dtype('int64')

In [10]:
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8]])
s = arr1[0,-2]
print(s)

3


In [11]:
arr1[0,:]

array([1, 2, 3, 4])

In [12]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr3[:5]

array([1, 2, 3, 4, 5])

zero matrix

In [16]:
np.zeros((6,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
np.full((40,40),560)

array([[560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       ...,
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560]])

In [19]:
from numpy import random

In [20]:
random.randint(100)

26

to get random values in matrix

In [21]:
np.random.rand(7,4)

array([[0.78028224, 0.15182461, 0.73623651, 0.23271378],
       [0.83809882, 0.60376874, 0.97633557, 0.47698924],
       [0.67531434, 0.21586509, 0.99037853, 0.44405756],
       [0.29373546, 0.50330844, 0.59449328, 0.55889512],
       [0.62364459, 0.91644225, 0.41865111, 0.04294226],
       [0.77338893, 0.59246828, 0.99067982, 0.22437472],
       [0.14953646, 0.21355722, 0.89623483, 0.61178878]])